AWSTemplateFormatVersion: '2010-09-09'
Description: Data processing stack for AWS Data Lake project (Glue)

Parameters:
  GlueDatabaseName:
    Type: String
    Description: The name of the Glue database
    Default: 'ecommerce_db_dev'

  DevDataLakeBucket:
    Type: String
    Description: The name of the S3 bucket for the data lake
    Default: 'ecommerce-data-lake-us-east-1-dev'

  GlueJobName:
    Description: The name of the Glue job
    Type: String
    Default: FullLoadAndCDCProcesserJob

  GlueScriptLocation:
    Description: The S3 location of the Glue script
    Type: String
    Default: s3://aws-glue-assets-730335322582-us-east-1/scripts/FullLoadAndCDCProcesser.py

  GlueIAMRoleName:
    Description: The name of the IAM role for the Glue job
    Type: String
    Default: GlueJobRole

Resources:
  GlueJobRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Ref GlueIAMRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'glue.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: GlueJobS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:GetObject'
                  - 's3:ListBucket'
                  - 's3:PutObject'
                  - 's3:DeleteObject'
                Resource:
                  - 'arn:aws:s3:::ecommerce-data-lake-us-east-1-dev'
                  - 'arn:aws:s3:::ecommerce-data-lake-us-east-1-dev/*'
                  - 'arn:aws:s3:::aws-glue-assets-730335322582-us-east-1'
                  - 'arn:aws:s3:::aws-glue-assets-730335322582-us-east-1/*'
              - Effect: 'Allow'
                Action:
                  - 'glue:*'
                Resource: '*'
                
  GlueS3AccessPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: 'GlueS3AccessPolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action:
              - 'glue:*'
            Resource: '*'
          - Effect: 'Allow'
            Action:
              - 's3:GetObject'
              - 's3:ListBucket'
            Resource:
              - 'arn:aws:s3:::ecommerce-data-lake-us-east-1-dev'
              - 'arn:aws:s3:::ecommerce-data-lake-us-east-1-dev/*'
          - Effect: 'Allow'
            Action:
              - 'glue:GetDatabase'
              - 'glue:GetTable'
              - 'glue:GetTables'
              - 'glue:CreateTable'
              - 'glue:UpdateTable'
              - 'glue:GetCatalog'
            Resource: 
              - 'arn:aws:glue:us-east-1:730335322582:catalog'
              - 'arn:aws:glue:us-east-1:730335322582:database/ecommerce_db_dev'
              - 'arn:aws:glue:us-east-1:730335322582:table/*'
      Roles:
        - !Ref GlueS3AccessRole

  GlueS3AccessRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'glue.amazonaws.com'
            Action: 'sts:AssumeRole'
      Path: "/"

  GlueDatabase:
    Type: 'AWS::Glue::Database'
    Properties:
      CatalogId: !Ref 'AWS::AccountId'
      DatabaseInput:
        Name: 'ecommerce_db_dev'
        Description: 'Development database for ecommerce data lake'

FullLoadAndCDCProcesserJob:
    Type: 'AWS::Glue::Job'
    Properties:
      Name: FullLoadAndCDCProcesserJob
      Role: !GetAtt GlueS3AccessRole.Arn
      Command:
        Name: 'glueetl'
        ScriptLocation: !Ref GlueScriptLocation
        PythonVersion: '3'
      DefaultArguments:
        '--TempDir': 's3://your-temp-dir/'
        '--enable-metrics': ''
        '--enable-continuous-log-filter': 'true'
      MaxRetries: 1
      GlueVersion: '2.0'
      NumberOfWorkers: 10
      WorkerType: 'G.1X'