AWSTemplateFormatVersion: '2010-09-09'
Description: Parent stack to manage nested stacks for AWS Data Lake project

Resources:
  StorageStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/mybucket/storage.yaml'

  ComputeStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/mybucket/compute.yaml'
      Parameters:
        LambdaS3Bucket: 'lambda-deployment-bucket-123456789012-us-east-1'
        LambdaS3Key: 'lambda-deployment-package.zip'

  DataProcessingStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/mybucket/data-processing.yaml'

  AnalyticsStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/mybucket/analytics.yaml'
