AWSTemplateFormatVersion: '2010-09-09'
Description: Parent stack to manage nested stacks for AWS Data Lake project

Resources:
  StorageStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://s3.us-east-1.amazonaws.com/aws-data-lake-project-repo/cloudformation/dev/storage.yaml'

  DataProcessingStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://s3.us-east-1.amazonaws.com/aws-data-lake-project-repo/cloudformation/dev/data-processing.yaml'

  AnalyticsStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://s3.us-east-1.amazonaws.com/aws-data-lake-project-repo/cloudformation/dev/analytics.yaml'
      Parameters:
        AthenaQueryResultsBucket: !GetAtt StorageStack.Outputs.AthenaQueryResultsBucket
