version: '3.8'

services:
  glue:
    build: .
    ports:
      - "8888:8888"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    volumes:
      - .:/opt
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
