AWSTemplateFormatVersion: '2010-09-09'
Description: Analytics stack for AWS Data Lake project

Parameters:
  Environment:
    Type: String
    Description: Deployment environment (e.g., dev, prod)
    AllowedValues:
      - dev
      - prod
    Default: dev

Resources:
  AthenaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'athena.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'AthenaS3AccessPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:ListBucket'
                Resource: 
                  - !Sub 'arn:aws:s3:::athena-query-results-${AWS::AccountId}-${AWS::Region}-${Environment}'
                  - !Sub 'arn:aws:s3:::athena-query-results-${AWS::AccountId}-${AWS::Region}-${Environment}/*'
              - Effect: 'Allow'
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'

Resources:
  AthenaWorkGroup:
    Type: 'AWS::Athena::WorkGroup'
    Properties:
      Name: !Sub data-lake-workgroup-${Environment}
      Description: Workgroup for Data Lake project
      State: ENABLED
      WorkGroupConfiguration:
        ResultConfiguration:
          OutputLocation: !Sub 's3://athena-query-results-${AWS::AccountId}-${AWS::Region}-${Environment}'
        EnforceWorkGroupConfiguration: true
        PublishCloudWatchMetricsEnabled: true

