AWSTemplateFormatVersion: '2010-09-09'
Description: Combined template for AWS CloudFormation to create an S3-based data lake with Athena, Glue, and IAM roles.

Parameters:
  LambdaS3Bucket:
    Description: S3 bucket where the Lambda deployment package is stored
    Type: String
    Default: 'lambda-deployment-bucket-123456789012-us-east-1'

  LambdaS3Key:
    Description: S3 key of the Lambda deployment package
    Type: String
    Default: 'lambda-deployment-package.zip'

Resources:
  # S3 Buckets
  AthenaQueryResultsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: athena-query-results-1234567890123-us-east-1
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ExpireQueryResults
            Status: Enabled
            ExpirationInDays: 30

  DevDataLakeBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: ecommerce-data-lake-dev
      AccessControl: Private
      LifecycleConfiguration:
        Rules:
          - Id: GlacierRule
            Status: Enabled
            Transitions:
              - StorageClass: GLACIER
                TransitionInDays: 30

  ProdDataLakeBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: ecommerce-data-lake-prod
      AccessControl: Private
      LifecycleConfiguration:
        Rules:
          - Id: GlacierRule
            Status: Enabled
            Transitions:
              - StorageClass: GLACIER
                TransitionInDays: 30

 # IAM Role for Lambda and Glue
  GlueS3AccessRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'LambdaS3AccessPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:PutObject'
                  - 's3:GetObject'
                  - 's3:ListBucket'
                Resource: 'arn:aws:s3:::*'
              - Effect: 'Allow'
                Action: 'glue:*'
                Resource: '*'

  AthenaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'athena.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'AthenaS3AccessPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:ListBucket'
                Resource: 
                  - 'arn:aws:s3:::athena-query-results-1234567890123-us-east-1'
                  - 'arn:aws:s3:::athena-query-results-1234567890123-us-east-1/*'
              - Effect: 'Allow'
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'

  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'LambdaS3AccessPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:PutObject'
                  - 's3:GetObject'
                  - 's3:ListBucket'
                Resource: 'arn:aws:s3:::*'
              - Effect: 'Allow'
                Action: 'logs:*'
                Resource: 'arn:aws:logs:*:*:*'

 # Lambda Function to Create S3 Folders
  S3PutObjectFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: 'index.handler'
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref LambdaS3Bucket
        S3Key: !Ref LambdaS3Key
      Runtime: 'python3.8'
      Timeout: 300

  # Custom Resources for Folder Structures
  DevDataLakeBucketFolders:
    Type: 'Custom::S3PutObject'
    Properties:
      ServiceToken: !GetAtt S3PutObjectFunction.Arn
      BucketName: !Ref DevDataLakeBucket
      FolderStructure:
        - raw-data/netsuite/full-load/orders/
        - raw-data/netsuite/full-load/customers/
        - raw-data/netsuite/full-load/transactions/
        - raw-data/netsuite/cdc/orders/
        - raw-data/netsuite/cdc/customers/
        - raw-data/netsuite/cdc/transactions/
        - raw-data/salesforce/full-load/leads/
        - raw-data/salesforce/full-load/opportunities/
        - raw-data/salesforce/full-load/accounts/
        - raw-data/salesforce/cdc/leads/
        - raw-data/salesforce/cdc/opportunities/
        - raw-data/salesforce/cdc/accounts/
        - raw-data/internal-db/full-load/hr/
        - raw-data/internal-db/full-load/finance/
        - raw-data/internal-db/full-load/inventory/
        - raw-data/internal-db/cdc/hr/
        - raw-data/internal-db/cdc/finance/
        - raw-data/internal-db/cdc/inventory/
        - raw-data/other-sources/source1/
        - raw-data/other-sources/source2/
        - processed-data/merged/orders/
        - processed-data/merged/customers/
        - processed-data/merged/transactions/
        - processed-data/sales/orders/
        - processed-data/sales/transactions/
        - processed-data/marketing/leads/
        - processed-data/marketing/campaigns/
        - processed-data/finance/revenue/
        - processed-data/finance/expenses/
        - processed-data/hr/employees/
        - processed-data/hr/payroll/
        - processed-data/other-domains/domain1/
        - processed-data/other-domains/domain2/
        - dbt_models/fact_tables/fact_sales/
        - dbt_models/fact_tables/fact_transactions/
        - dbt_models/dimension_tables/dim_customers/
        - dbt_models/dimension_tables/dim_products/
        - analytics-consumption/bi-tools/tableau/
        - analytics-consumption/bi-tools/powerbi/
        - analytics-consumption/data-science/models/
        - analytics-consumption/data-science/predictions/
        - analytics-consumption/aggregated-data/monthly-reports/
        - analytics-consumption/aggregated-data/quarterly-reports/
        - metadata/data-catalog/
        - metadata/data-lineage/

  ProdDataLakeBucketFolders:
    Type: 'Custom::S3PutObject'
    Properties:
      ServiceToken: !GetAtt S3PutObjectFunction.Arn
      BucketName: !Ref ProdDataLakeBucket
      FolderStructure:
        - raw-data/netsuite/full-load/orders/
        - raw-data/netsuite/full-load/customers/
        - raw-data/netsuite/full-load/transactions/
        - raw-data/netsuite/cdc/orders/
        - raw-data/netsuite/cdc/customers/
        - raw-data/netsuite/cdc/transactions/
        - raw-data/salesforce/full-load/leads/
        - raw-data/salesforce/full-load/opportunities/
        - raw-data/salesforce/full-load/accounts/
        - raw-data/salesforce/cdc/leads/
        - raw-data/salesforce/cdc/opportunities/
        - raw-data/salesforce/cdc/accounts/
        - raw-data/internal-db/full-load/hr/
        - raw-data/internal-db/full-load/finance/
        - raw-data/internal-db/full-load/inventory/
        - raw-data/internal-db/cdc/hr/
        - raw-data/internal-db/cdc/finance/
        - raw-data/internal-db/cdc/inventory/
        - raw-data/other-sources/source1/
        - raw-data/other-sources/source2/
        - processed-data/merged/orders/
        - processed-data/merged/customers/
        - processed-data/merged/transactions/
        - processed-data/sales/orders/
        - processed-data/sales/transactions/
        - processed-data/marketing/leads/
        - processed-data/marketing/campaigns/
        - processed-data/finance/revenue/
        - processed-data/finance/expenses/
        - processed-data/hr/employees/
        - processed-data/hr/payroll/
        - processed-data/other-domains/domain1/
        - processed-data/other-domains/domain2/
        - dbt_models/fact_tables/fact_sales/
        - dbt_models/fact_tables/fact_transactions/
        - dbt_models/dimension_tables/dim_customers/
        - dbt_models/dimension_tables/dim_products/
        - analytics-consumption/bi-tools/tableau/
        - analytics-consumption/bi-tools/powerbi/
        - analytics-consumption/data-science/models/
        - analytics-consumption/data-science/predictions/
        - analytics-consumption/aggregated-data/monthly-reports/
        - analytics-consumption/aggregated-data/quarterly-reports/
        - metadata/data-catalog/
        - metadata/data-lineage/

  # Glue Database
  GlueDatabase:
    Type: 'AWS::Glue::Database'
    Properties:
      CatalogId: !Ref 'AWS::AccountId'
      DatabaseInput:
        Name: 'ecommerce_db_dev'
        Description: 'Development database for ecommerce data lake'

  # IAM Role for Glue Crawler
  GlueCrawlerRole:
    Type: 'AWS::IAM::Role'
    Properties: 
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'glue.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'GlueCrawlerPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:ListBucket'
                Resource: 
                  - 'arn:aws:s3:::ecommerce-data-lake-dev'
                  - 'arn:aws:s3:::ecommerce-data-lake-dev/*'
                  - 'arn:aws:s3:::ecommerce-data-lake-prod'
                  - 'arn:aws:s3:::ecommerce-data-lake-prod/*'
              - Effect: 'Allow'
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'

  # Glue Crawler for Full Load
  FullLoadCrawler:
    Type: 'AWS::Glue::Crawler'
    Properties:
      Name: 'full-load-crawler'
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref GlueDatabase
      Targets:
        S3Targets:
          - Path: 's3://ecommerce-data-lake-dev/raw-data/netsuite/full-load/'
      SchemaChangePolicy:
        UpdateBehavior: 'UPDATE_IN_DATABASE'
        DeleteBehavior: 'LOG'

  # Glue Crawler for CDC
  CDCCrawler:
    Type: 'AWS::Glue::Crawler'
    Properties:
      Name: 'cdc-crawler'
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref GlueDatabase
      Targets:
        S3Targets:
          - Path: 's3://ecommerce-data-lake-dev/raw-data/netsuite/cdc/'
      SchemaChangePolicy:
        UpdateBehavior: 'UPDATE_IN_DATABASE'
        DeleteBehavior: 'LOG'

# Athena Workgroup
  AthenaWorkGroup:
    Type: 'AWS::Athena::WorkGroup'
    Properties:
      Name: data-lake-workgroup
      State: ENABLED
      Description: Workgroup for Data Lake project
      WorkGroupConfiguration:
        ResultConfiguration:
          OutputLocation: !Sub 's3://${AthenaQueryResultsBucket}/'
        EnforceWorkGroupConfiguration: true
        PublishCloudWatchMetricsEnabled: true
        RequesterPaysEnabled: false

Outputs:
  AthenaQueryResultsBucket:
    Description: Name of the development Athena results S3 bucket
    Value: !Ref AthenaQueryResultsBucket
  
  DevBucketName:
    Description: Name of the development data lake S3 bucket
    Value: !Ref DevDataLakeBucket

  ProdBucketName:
    Description: Name of the production data lake S3 bucket
    Value: !Ref ProdDataLakeBucket

  GlueS3AccessRoleArn:
    Description: ARN of the IAM role for Glue
    Value: !GetAtt GlueS3AccessRole.Arn

  AthenaExecutionRole:
    Description: ARN of the IAM role for Athena
    Value: !GetAtt AthenaExecutionRole.Arn

  LambdaExecutionRoleArn:
    Description: ARN of the IAM role for Lambda
    Value: !GetAtt LambdaExecutionRole.Arn

  GlueDatabaseName:
    Description: Name of the Glue database
    Value: !Ref GlueDatabase

  FullLoadCrawlerName:
    Description: Name of the Glue crawler for full load
    Value: !Ref FullLoadCrawler

  CDCCrawlerName:
    Description: Name of the Glue crawler for CDC
    Value: !Ref CDCCrawler
