AWSTemplateFormatVersion: '2010-09-09'
Description: Data processing stack for AWS Data Lake project (Glue) with environment separation

Parameters:
  Environment:
    Type: String
    Description: Deployment environment (e.g., dev, prod)
    AllowedValues:
      - dev
      - prod
    Default: dev

  GlueDatabaseName:
    Type: String
    Description: The name of the Glue database
    Default: 'ecommerce_db_${Environment}'

  DataLakeBucket:
    Type: String
    Description: The name of the S3 bucket for the data lake
    Default: 'ecommerce-data-lake-${AWS::Region}-${Environment}' 

  FullLoadAndCDCProcesserGlueJobName:
    Description: The name of the Glue job
    Type: String
    Default: FullLoadAndCDCProcesserJob

  FullLoadAndCDCProcesserGlueScriptLocation:
    Description: The S3 location of the FullLoadAndCDCProcesser Glue script
    Type: String
    Default: 's3://aws-glue-assets-${AWS::AccountId}-${AWS::Region}-${Environment}/scripts/FullLoadAndCDCProcesser.py'

  GlueIAMRoleName:
    Description: The name of the IAM role for the Glue job
    Type: String
    Default: GlueJobRole-${Environment}

  RawS3Path:
    Type: String
    Description: S3 path to the raw data
    Default: 's3://ecommerce-data-lake-${AWS::Region}-${Environment}/01_raw/'

  StagingS3Path:
    Type: String
    Description: S3 path to the staging data
    Default: 's3://ecommerce-data-lake-${AWS::Region}-${Environment}/02_staging/'

  PreprocessedS3Path:
    Type: String
    Description: S3 path to the preprocessed data
    Default: 's3://ecommerce-data-lake-${AWS::Region}-${Environment}/03_preprocessed/'

  MasterS3Path:
    Type: String
    Description: S3 path to the master data
    Default: 's3://ecommerce-data-lake-${AWS::Region}-${Environment}/04_master/'
    
  CuratedS3Path:
    Type: String
    Description: S3 path to the curated data
    Default: 's3://ecommerce-data-lake-${AWS::Region}-dev/06_curated/'

  IcebergJarS3Path:
    Description: S3 path to the Iceberg JAR file
    Type: String
    Default: 's3://aws-glue-assets-${AWS::AccountId}-${AWS::Region}-${Environment}/dependencies/iceberg-spark3-runtime-0.12.0.jar' 

  PyDeequJarS3Path:
    Description: S3 path to the pydeequ JAR file
    Type: String
    Default: 's3://aws-glue-assets-${AWS::AccountId}-${AWS::Region}-${Environment}/dependencies/deequ-glue-1.0-SNAPSHOT-jar-with-dependencies.jar'  

Resources:
  GlueDatabase:
    Type: 'AWS::Glue::Database'
    Properties:
      CatalogId: !Ref 'AWS::AccountId'
      DatabaseInput:
        Name: !Sub 'ecommerce_db_${Environment}'
        Description: 'Database for ecommerce data lake'

  FullLoadAndCDCProcesserGlueJob:
    Type: 'AWS::Glue::Job'
    Properties:
      Name: !Sub '${FullLoadAndCDCProcesserGlueJobName}-${Environment}'
      Role: !GetAtt GlueJobRole.Arn
      Command:
        Name: glueetl
        ScriptLocation: !Ref FullLoadAndCDCProcesserGlueScriptLocation
        PythonVersion: '3'
      DefaultArguments:
        "--RAW_S3_PATH": !Ref RawS3Path
        "--STAGING_S3_PATH": !Ref StagingS3Path
        "--PREPROCESSED_S3_PATH": !Ref PreprocessedS3Path
        "--MASTER_S3_PATH": !Ref MasterS3Path
        "--CURATED_S3_PATH": !Ref CuratedS3Path
        "--enable-continuous-cloudwatch-log": "true"
        "--enable-continuous-log-filter": "true"
        "--enable-metrics": "true"
        '--additional-python-modules': 'pydeequ'
        '--extra-jars': !Sub "${IcebergJarS3Path},${PyDeequJarS3Path}"
        '--TempDir': !Sub 's3://temp-${AWS::AccountId}-${AWS::Region}-${Environment}'
        '--SPARK_VERSION': '3.1' #Set the SPARK_VERSION environment variable
      GlueVersion: '3.0'
      MaxRetries: 1
      LogUri: !Sub "s3://${AWS::AccountId}/aws-glue/jobs/logs-v2-${Environment}"
      MaxCapacity: 2.0
      Timeout: 2880