AWSTemplateFormatVersion: '2010-09-09'
Description: Glue Crawlers and IAM Roles for Data Lake

Parameters:
  Environment:
    Type: String
    Description: Deployment environment (e.g., dev, prod)
    AllowedValues:
      - dev
      - prod
    Default: dev

Resources:
  # IAM Role for Glue Crawlers
  GlueCrawlerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub 'GlueCrawlerRole-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'glue.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub 'GlueCrawlerPolicy-${Environment}'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:ListBucket'
                Resource: 
                  - 'arn:aws:s3:::ecommerce-data-lake-us-east-1-${Environment}/*'
                  - 'arn:aws:s3:::ecommerce-data-lake-us-east-1-${Environment}'
              - Effect: 'Allow'
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'

  # Glue Crawlers for each layer
  RawDataCrawler:
    Type: 'AWS::Glue::Crawler'
    Properties:
      Name: 'raw-data-crawler-${Environment}'
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: 'ecommerce_db_${Environment}'
      Targets:
        S3Targets:
          - Path: 's3://ecommerce-data-lake-us-east-1-${Environment}/01_raw/'
      SchemaChangePolicy:
        UpdateBehavior: 'UPDATE_IN_DATABASE'
        DeleteBehavior: 'LOG'

  StagingDataCrawler:
    Type: 'AWS::Glue::Crawler'
    Properties:
      Name: 'staging-data-crawler-${Environment}'
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: 'ecommerce_db_${Environment}'
      Targets:
        S3Targets:
          - Path: 's3://ecommerce-data-lake-us-east-1-${Environment}/02_staging/'
      SchemaChangePolicy:
        UpdateBehavior: 'UPDATE_IN_DATABASE'
        DeleteBehavior: 'LOG'

  PreprocessedDataCrawler:
    Type: 'AWS::Glue::Crawler'
    Properties:
      Name: 'preprocessed-data-crawler-${Environment}'
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: 'ecommerce_db_${Environment}'
      Targets:
        S3Targets:
          - Path: 's3://ecommerce-data-lake-us-east-1-${Environment}/03_preprocessed/'
      SchemaChangePolicy:
        UpdateBehavior: 'UPDATE_IN_DATABASE'
        DeleteBehavior: 'LOG'

  MasterDataCrawler:
    Type: 'AWS::Glue::Crawler'
    Properties:
      Name: 'master-data-crawler-${Environment}'
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: 'ecommerce_db_${Environment}'
      Targets:
        S3Targets:
          - Path: 's3://ecommerce-data-lake-us-east-1-${Environment}/04_master/'
      SchemaChangePolicy:
        UpdateBehavior: 'UPDATE_IN_DATABASE'
        DeleteBehavior: 'LOG'

  CuratedDataCrawler:
    Type: 'AWS::Glue::Crawler'
    Properties:
      Name: 'curated-data-crawler-${Environment}'
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: 'ecommerce_db_${Environment}'
      Targets:
        S3Targets:
          - Path: 's3://ecommerce-data-lake-us-east-1-${Environment}/06_curated/'
      SchemaChangePolicy:
        UpdateBehavior: 'UPDATE_IN_DATABASE'
        DeleteBehavior: 'LOG'