AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function to run dbt

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Deployment environment (dev or prod)

Resources:
  RunDbtLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaDBTExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                  - glue:StartJobRun
                  - glue:GetJobRun
                  - glue:GetJobRuns
                  - glue:BatchStopJobRun
                Resource: "*"

  RunDbtLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${Environment}-run_dbt_lambda"
      Handler: index.handler
      Role: !GetAtt RunDbtLambdaExecutionRole.Arn
      Code:
        S3Bucket: !Sub "aws-lambda-${AWS::AccountId}-${AWS::Region}-${Environment}"
        S3Key: "run_dbt_lambda.zip"
      Runtime: python3.8
      Timeout: 300
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
