# glue_jobs/etl/full_load_and_cdc/config.yaml

dev:
  RAW_S3_PATH: "s3://ecommerce-data-lake-us-east-1-dev/01_raw/"
  STAGING_S3_PATH: "s3://ecommerce-data-lake-us-east-1-dev/02_staging/"
  PREPROCESSED_S3_PATH: "s3://ecommerce-data-lake-us-east-1-dev/03_preprocessed/"
  MASTER_S3_PATH: "s3://ecommerce-data-lake-us-east-1-dev/04_master/"
  CURATED_S3_PATH: "s3://ecommerce-data-lake-us-east-1-dev/06_curated/"
prod:
  RAW_S3_PATH: "s3://ecommerce-data-lake-us-east-1-prod/01_raw/"
  STAGING_S3_PATH: "s3://ecommerce-data-lake-us-east-1-prod/02_staging/"
  PREPROCESSED_S3_PATH: "s3://ecommerce-data-lake-us-east-1-prod/03_preprocessed/"
  MASTER_S3_PATH: "s3://ecommerce-data-lake-us-east-1-prod/04_master/"
  CURATED_S3_PATH: "s3://ecommerce-data-lake-us-east-1-prod/06_curated/"
common:
  TABLE_NAME: "orders"
  PROCESS_TYPE: "full_load"
  SOURCE: "netSuite"
