name: Deploy Glue Job Script 

on:
  push:
    branches:
      - main
      - DEV
    paths:
      - 'glue/scripts/'
      - '.github/workflows/deploy-glue-job.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, prod]  # Add environments here
        region: [us-east-1]
        account: [730335322582]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Sync Glue script to S3
      run: |
        aws s3 cp glue/scripts/ s3://aws-glue-assets-${{ matrix.account }}-${{ matrix.region }}-${{ matrix.environment }}/scripts/

    - name: Deploy CloudFormation stack
      run: |
        aws cloudformation deploy \
          --template-file cloudformation/data-processing.yaml \
          --stack-name data-processing-stack \
          --capabilities CAPABILITY_NAMED_IAM
